package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        add {
            password("liquibasePassword", "credentialsJSON:c0f482be-b812-4979-8460-21a077f3ac2f")
        }
    }

    expectSteps {
        script {
            name = "liquibase version"
            scriptContent = "liquibase --version"
        }
        script {
            name = "liquibase update"
            scriptContent = "liquibase --logLevel=debug --defaultsFile=cf-mysql-01.properties update"
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            scriptContent = "liquibase --logLevel=debug --password=%liquibasePassword% --defaultsFile=cf-mysql-01.properties update"
        }
    }
}
