package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        add {
            param("env.current_build_date", "dummy")
        }
    }

    expectSteps {
        script {
            name = "Capture Start Time"
            scriptContent = "export START_TIME=${'$'}(date)"
        }
        script {
            name = "Liquibase version"
            scriptContent = "liquibase --version"
        }
        script {
            name = "Liquibase validate"
            scriptContent = "liquibase --logLevel=debug --password=%liquibasePassword% --defaultsFile=cf-mysql-01.properties validate"
        }
        script {
            name = "Liquibase update"
            scriptContent = "liquibase --logLevel=debug --password=%liquibasePassword% --defaultsFile=cf-mysql-01.properties update"
        }
        script {
            name = "Send Metrics"
            scriptContent = """curl -k -u "x:edca663a-18da-4532-a766-e8726545ce4c" https://localhost:8088/services/collector/event -d '{"sourcetype": "teamcity", "event": { "message":"Build Completed", "startTime": "${'$'}{START_TIME}", "endTime": "${'$'}(date)"}}'"""
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            scriptContent = """
                export current_build_date_format="+%%Y.%%m.%%d"
                export current_build_date="${'$'}(date ${'$'}current_build_date_format)"
                echo "##teamcity[setParameter name='env.current_build_date' value='${'$'}current_build_date']"
            """.trimIndent()
        }
        update<ScriptBuildStep>(4) {
            scriptContent = """curl -k -u "x:edca663a-18da-4532-a766-e8726545ce4c" https://cf-splunk-01:8088/services/collector/event -d '{"sourcetype": "teamcity", "event": { "message":"Build Completed", "startTime": "%env.current_build_date%", "endTime": "${'$'}(date)"}}'"""
        }
    }
}
